# Generated by Django 4.1.7 on 2023-03-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('password_confirm', models.CharField(max_length=50)),
                ('db_choices', models.CharField(choices=[('scopus', 'Scopus'), ('pubmed', 'PubMed'), ('dimensions', 'Dimensions'), ('web_of_science', 'Web of Science')], max_length=200)),
            ],
        ),
    ]
